apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: details-reviews-viewer
  namespace: default
spec:
  rules:
  - services: [
      "details.default.svc.cluster.local",
      "reviews.default.svc.cluster.local"
    ]
    methods: ["GET"]
