apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: bookinfo-viewer
  namespace: default
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
    constraints:
    - key: "destination.labels[app]"
      values: ["productpage", "details", "reviews", "ratings"]
